import mongoose from "mongoose";

const diamondStockSchema = new mongoose.Schema({
  stockNumber: { type: String, required: true },
  availability: { type: String, required: true },
  shape: { type: String, required: true },
  weight: { type: Number, required: true },
  color: { type: String, required: true },
  clarity: { type: String, required: true },
  cutGrade: { type: String, required: true },
  polish: { type: String, required: true },
  symmetry: { type: String, required: true },
  fluorescenceIntensity: { type: String, required: true },
  fluorescenceColor: { type: String },  // Optional
  measurements: { type: String, required: true },
  BGM: { type: String },
  eyeClean: { type: String },
  lab: { type: String, required: true },
  reportNumber: { type: String, required: true },
  rapLabReportID: { type: String },
  treatment: { type: String },
  rapNetPrice: { type: Number, required: true },
  rapNetDiscountPercent: { type: Number, required: true },
  cashPrice: { type: Number },
  cashPriceDiscountPercent: { type: Number },
  buyNowPricePerCt: { type: Number },
  buyNowRapPercent: { type: Number },
  depthPercent: { type: Number, required: true },
  tablePercent: { type: Number, required: true },
  girdleThin: { type: String },
  girdleThick: { type: String },
  girdlePercent: { type: Number },
  girdleCondition: { type: String },
  culetSize: { type: String },
  culetCondition: { type: String },
  crownHeight: { type: Number },
  crownAngle: { type: Number },
  pavilionDepth: { type: Number },
  pavilionAngle: { type: Number },
  laserInscription: { type: String },
  certComment: { type: String },
  keyToSymbols: { type: String },
  memberComment: { type: String },
  starLength: { type: Number },
  shade: { type: String },
  whiteInclusion: { type: String },
  blackInclusion: { type: String },
  openInclusion: { type: String },
  milky: { type: String },
  fancyColor: { type: String },
  fancyColorIntensity: { type: String },
  fancyColorOvertone: { type: String },
  country: { type: String },
  state: { type: String },
  city: { type: String },
  brand: { type: String },
  sellerSpec: { type: String },
  sarineID: { type: String },
  reportFileName: { type: String },
  report2FileName: { type: String },
  websiteLink: { type: String },
  images: [String],        
  videos: [String],        
  documents: [{
    file: String,
    type: String
  }],
  tradeShow: { type: String },
  reportType: { type: String },
  labLocation: { type: String },
  pairStockNumber: { type: String },
  isMatchedPairSeparable: { type: Boolean },
  allowRapLinkFeed: { type: Boolean },
  parcelStones: { type: String },
  tracrID: { type: String },
  roughSource: { type: String },
  mine: { type: String },
  owner: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Seller",
    required: true
  }
}, { timestamps: true });

export const DiamondStock = mongoose.model('DiamondStock', diamondStockSchema);
